/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ImportDataRouteImport } from './routes/import-data'
import { Route as DataRouteImport } from './routes/data'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsOverlaysRouteImport } from './routes/components.overlays'
import { Route as ComponentsNavigationRouteImport } from './routes/components.navigation'
import { Route as ComponentsInputsRouteImport } from './routes/components.inputs'
import { Route as ComponentsFoundationsRouteImport } from './routes/components.foundations'
import { Route as ComponentsCustomRouteImport } from './routes/components.custom'
import { Route as AnalysisRunIdRouteImport } from './routes/analysis_.$runId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportDataRoute = ImportDataRouteImport.update({
  id: '/import-data',
  path: '/import-data',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsOverlaysRoute = ComponentsOverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsNavigationRoute = ComponentsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsInputsRoute = ComponentsInputsRouteImport.update({
  id: '/inputs',
  path: '/inputs',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsFoundationsRoute = ComponentsFoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => ComponentsRoute,
} as any)
const ComponentsCustomRoute = ComponentsCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => ComponentsRoute,
} as any)
const AnalysisRunIdRoute = AnalysisRunIdRouteImport.update({
  id: '/analysis_/$runId',
  path: '/analysis/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/components': typeof ComponentsRouteWithChildren
  '/data': typeof DataRoute
  '/import-data': typeof ImportDataRoute
  '/imports': typeof ImportsRoute
  '/settings': typeof SettingsRoute
  '/traces': typeof TracesRoute
  '/welcome': typeof WelcomeRoute
  '/analysis/$runId': typeof AnalysisRunIdRoute
  '/components/custom': typeof ComponentsCustomRoute
  '/components/foundations': typeof ComponentsFoundationsRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/overlays': typeof ComponentsOverlaysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/components': typeof ComponentsRouteWithChildren
  '/data': typeof DataRoute
  '/import-data': typeof ImportDataRoute
  '/imports': typeof ImportsRoute
  '/settings': typeof SettingsRoute
  '/traces': typeof TracesRoute
  '/welcome': typeof WelcomeRoute
  '/analysis/$runId': typeof AnalysisRunIdRoute
  '/components/custom': typeof ComponentsCustomRoute
  '/components/foundations': typeof ComponentsFoundationsRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/overlays': typeof ComponentsOverlaysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/components': typeof ComponentsRouteWithChildren
  '/data': typeof DataRoute
  '/import-data': typeof ImportDataRoute
  '/imports': typeof ImportsRoute
  '/settings': typeof SettingsRoute
  '/traces': typeof TracesRoute
  '/welcome': typeof WelcomeRoute
  '/analysis_/$runId': typeof AnalysisRunIdRoute
  '/components/custom': typeof ComponentsCustomRoute
  '/components/foundations': typeof ComponentsFoundationsRoute
  '/components/inputs': typeof ComponentsInputsRoute
  '/components/navigation': typeof ComponentsNavigationRoute
  '/components/overlays': typeof ComponentsOverlaysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/components'
    | '/data'
    | '/import-data'
    | '/imports'
    | '/settings'
    | '/traces'
    | '/welcome'
    | '/analysis/$runId'
    | '/components/custom'
    | '/components/foundations'
    | '/components/inputs'
    | '/components/navigation'
    | '/components/overlays'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/components'
    | '/data'
    | '/import-data'
    | '/imports'
    | '/settings'
    | '/traces'
    | '/welcome'
    | '/analysis/$runId'
    | '/components/custom'
    | '/components/foundations'
    | '/components/inputs'
    | '/components/navigation'
    | '/components/overlays'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/components'
    | '/data'
    | '/import-data'
    | '/imports'
    | '/settings'
    | '/traces'
    | '/welcome'
    | '/analysis_/$runId'
    | '/components/custom'
    | '/components/foundations'
    | '/components/inputs'
    | '/components/navigation'
    | '/components/overlays'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  ComponentsRoute: typeof ComponentsRouteWithChildren
  DataRoute: typeof DataRoute
  ImportDataRoute: typeof ImportDataRoute
  ImportsRoute: typeof ImportsRoute
  SettingsRoute: typeof SettingsRoute
  TracesRoute: typeof TracesRoute
  WelcomeRoute: typeof WelcomeRoute
  AnalysisRunIdRoute: typeof AnalysisRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-data': {
      id: '/import-data'
      path: '/import-data'
      fullPath: '/import-data'
      preLoaderRoute: typeof ImportDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/overlays': {
      id: '/components/overlays'
      path: '/overlays'
      fullPath: '/components/overlays'
      preLoaderRoute: typeof ComponentsOverlaysRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/navigation': {
      id: '/components/navigation'
      path: '/navigation'
      fullPath: '/components/navigation'
      preLoaderRoute: typeof ComponentsNavigationRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/inputs': {
      id: '/components/inputs'
      path: '/inputs'
      fullPath: '/components/inputs'
      preLoaderRoute: typeof ComponentsInputsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/foundations': {
      id: '/components/foundations'
      path: '/foundations'
      fullPath: '/components/foundations'
      preLoaderRoute: typeof ComponentsFoundationsRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/components/custom': {
      id: '/components/custom'
      path: '/custom'
      fullPath: '/components/custom'
      preLoaderRoute: typeof ComponentsCustomRouteImport
      parentRoute: typeof ComponentsRoute
    }
    '/analysis_/$runId': {
      id: '/analysis_/$runId'
      path: '/analysis/$runId'
      fullPath: '/analysis/$runId'
      preLoaderRoute: typeof AnalysisRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ComponentsRouteChildren {
  ComponentsCustomRoute: typeof ComponentsCustomRoute
  ComponentsFoundationsRoute: typeof ComponentsFoundationsRoute
  ComponentsInputsRoute: typeof ComponentsInputsRoute
  ComponentsNavigationRoute: typeof ComponentsNavigationRoute
  ComponentsOverlaysRoute: typeof ComponentsOverlaysRoute
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsCustomRoute: ComponentsCustomRoute,
  ComponentsFoundationsRoute: ComponentsFoundationsRoute,
  ComponentsInputsRoute: ComponentsInputsRoute,
  ComponentsNavigationRoute: ComponentsNavigationRoute,
  ComponentsOverlaysRoute: ComponentsOverlaysRoute,
}

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(
  ComponentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
  DataRoute: DataRoute,
  ImportDataRoute: ImportDataRoute,
  ImportsRoute: ImportsRoute,
  SettingsRoute: SettingsRoute,
  TracesRoute: TracesRoute,
  WelcomeRoute: WelcomeRoute,
  AnalysisRunIdRoute: AnalysisRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
